services:
  hardhat-node:
    build:
      context: .
      dockerfile: ./hardhat-node/Dockerfile
    container_name: democracy-hardhat-node
    ports:
      - "8545:8545"
    environment:
      - NODE_ENV=production
    user: "clistenes"
    networks:
      - democracy
    deploy:
      resources:
        limits:
          memory: 512M

  deployer-interactor:
    build:
      context: ./dapp
    container_name: democracy-deployer-interactor
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=${ENVIRONMENT:-production}
      - BLOCKCHAIN_URL=${BLOCKCHAIN_URL:-http://hardhat-node:8545}
    user: "clistenes"
    depends_on:
      - hardhat-node
    networks:
      - democracy
    volumes: # Eliminar cuando haya terminado de desarrollar
      - ./dapp:/app
    deploy:
      resources:
        limits:
          memory: 512M

  frontend:
    build:
      context: ./frontend
    container_name: democracy-frontend
    ports:
      - "80:5173"
      - "8080:4173"
    environment:
      - NODE_ENV=${ENVIRONMENT:-development}
      - VITE_BACKEND_URL=${BACKEND_URL:-http://localhost:8000/api/v1}
      - VITE_CONTRACT_API_URL=${CONTRACT_API_URL:-http://localhost:3000}
    user: "clistenes"
    depends_on:
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_healthy
    networks:
      - democracy
    volumes: # Eliminar cuando haya terminado de desarrollar
      - ./frontend:/app
      - /app/node_modules

  qdrant:
    image: qdrant/qdrant:latest
    container_name: democracy-qdrant
    restart: unless-stopped
    networks:
      - ragnet
    volumes:
      - qdrant_data:/qdrant/storage
  
  rabbitmq:
    build:
      context: ./rabbitmq
      args:
        RABBITMQ_USER: ${RABBITMQ_USER:-rabbituser}
        RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-securepassword123}
    container_name: democracy-rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_LOAD_DEFINITIONS=/etc/rabbitmq/definitions.json
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ragnet

  mysql:
    image: mysql:9.3
    container_name: democracy-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=${MYSQL_DATABASE:-democracy}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ragnet

  backend:
    build:
      context: ./backend
    container_name: democracy-backend
    user: "clistenes"
    volumes:
      - ./backend:/app # Eliminar cuando haya terminado de desarrollar
      - ./data:/data
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_URL=${MYSQL_URL:-mysql+asyncmy://user:password@mysql:3306/democracy}
      - RABBITMQ_URL=${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672/democracy}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE:-democracy}
      - UPLOAD_DIR=/data/uploads
      - FRONTEND_HOST=${FRONTEND_HOST:-http://localhost}
      - QDRANT_URL=${QDRANT_HOST:-http://qdrant:6333/}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-all-MiniLM-L6-v2}
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - qdrant
      - mysql
      - llm
    networks:
      - ragnet

  worker:
    build: ./worker
    container_name: democracy-worker
    volumes:
      - ./data:/data
    depends_on:
      rabbitmq:
        condition: service_healthy
      qdrant:
        condition: service_started
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672/democracy}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE:-democracy}
      - QDRANT_URL=${QDRANT_HOST:-http://qdrant:6333/}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-all-MiniLM-L6-v2}
      - UPLOAD_DIR=/data/uploads
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
    networks:
      - ragnet
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f src/worker/main.py || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia

  llm:
    build:
      context: ./llm
    container_name: democracy-llm
    restart: unless-stopped
    runtime: nvidia
    entrypoint: >
      sh -c '
        if [ "$${ENVIRONMENT}" = "development" ]; then
          ollama serve & 
          echo "Esperando a que Ollama esté disponible..." && 
          until curl -s http://localhost:11434 > /dev/null; do sleep 2; done && 
          echo "Descargando modelo $${LLM_MODEL:-llama2}..." && 
          ollama pull $${LLM_MODEL:-llama2} && 
          tail -f /dev/null;
        else
          echo "Entorno de producción - solo lanzando Ollama...";
          exec ollama serve;
        fi
      '
    ports: # TODO: eliminar
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_MODELS=/root/.ollama
      - LLM_MODEL=${LLM_MODEL:-llama2}
    networks:
      - ragnet
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
        limits:
          memory: 8g

volumes:
  qdrant_data:
  mysql_data:
  ollama_models:

networks:
  democracy:
    driver: bridge
  ragnet:
    driver: bridge

